packages:
    - apps/*
    - packages/*

catalog:
    typescript: 5.9.3
    '@tsconfig/strictest': 2.0.8
    '@tsconfig/vite-react': 7.0.2
    '@types/node': 25.5.0
    '@shuiyangsuan/tsconfig': 0.0.3

onlyBuiltDependencies:
    - '@vscode/vsce-sign'
    - bun
    - keytar
